/// Generated by AssetsRefGenerator on 2020/10/22
class Res {
  static const String icon = "images/icon.png";
  static const String icon_back = "images/icon_back.png";
  static const String image_company = "images/about/image_company.png";
}
